api_version: 1
provider: Kumbuka
id: me.kumbuka.autolinks
name: Automatic Links
version: 1.1.1
description: Turn plain URLs and email addresses into links.
default_enabled: true
modules:
  - type: markdown-syntax
    id: autolinks
    syntax: linkify
    usage:
      - contains: "://"
      - contains: "www."
      - contains: "@"
permissions: []
