api_version: 1
provider: Kumbuka
id: me.kumbuka.callouts
name: Callouts
version: 1.0.2
description: Note, warning, and other callout blocks
default_enabled: true
modules:
  - type: renderer-extension
    id: callouts
    stage: preprocess
    usage:
      - contains: "!!! "
permissions: []

