#!/usr/bin/env bash
# Generate plugin pages in a staging directory before changing the docs checkout.
set -euo pipefail
export LC_ALL=C
root=$(cd "$(dirname "$0")/../.." && pwd)
docs=../docs
while (($#)); do
  case $1 in
    --plugins) root=${2:?missing plugin directory}; shift 2 ;;
    --docs) docs=${2:?missing docs directory}; shift 2 ;;
    *) echo "Usage: $0 [--plugins DIR] [--docs DIR]" >&2; exit 2 ;;
  esac
done
for tool in yq jq; do command -v "$tool" >/dev/null || { echo "$tool is required (use Mike Farah yq v4)." >&2; exit 1; }; done
stage=$(mktemp -d "${TMPDIR:-/tmp}/kumbuka-docs.XXXXXX")
trap 'rm -rf "$stage"' EXIT
trap 'exit 130' INT
trap 'exit 143' TERM
header='<!-- Generated by kumbuka-me/plugins scripts/docs. Edit the plugin README, manifest or preview in that repository. -->'
mkdir -p "$stage/content/plugins/packages" "$stage/assets/plugins"
index="$stage/content/plugins/catalog.md"
printf '%s\n\n# Plugin catalog\n\n' "$header" > "$index"
cat >> "$index" <<'INTRO'
Browse the first-party Kumbuka plugins. These pages follow the plugins repository's main branch; available releases are listed on each plugin's release page.

See [Plugin administration](../administration/plugins.md) for installation and updates.
INTRO
count=0
for manifest in "$root"/*/plugin.yaml; do
  [[ -f $manifest ]] || continue
  dir=${manifest%/plugin.yaml}; slug=${dir##*/}
  metadata=$(yq -o=json '.' "$manifest")
  jq -e 'all(.id,.name,.version,.description; type == "string" and length > 0) and ((.permissions // []) | type == "array" and all(.[]; type == "string"))' <<< "$metadata" >/dev/null
  id=$(jq -r .id <<< "$metadata"); name=$(jq -r .name <<< "$metadata")
  version=$(jq -r .version <<< "$metadata"); description=$(jq -r .description <<< "$metadata")
  permissions=$(jq -r 'if (.permissions // [] | length) == 0 then "None" else "`" + (.permissions | join("`, `")) + "`" end' <<< "$metadata")
  [[ -s $dir/README.md && -s $dir/assets/preview.png ]] || { echo "$slug: missing README or preview" >&2; exit 1; }
  page="$stage/content/plugins/packages/$slug.md"
  {
    printf '%s\n\n# %s\n\n%s\n\n' "$header" "$name" "$description"
    printf '![%s preview](/assets/plugins/%s/preview.png)\n\n' "$name" "$slug"
    printf -- '- Plugin ID: `%s`\n- Source version: `%s`\n- Permissions: %s\n\n' "$id" "$version" "$permissions"
    printf '[Source](https://github.com/kumbuka-me/plugins/tree/main/%s) · [Releases](https://github.com/kumbuka-me/plugins/releases?q=%s%%2Fv) · [Installation](../../administration/plugins.md)\n\n' "$slug" "$slug"
    awk -v slug="$slug" -f "$(dirname "$0")/readme.awk" "$dir/README.md"
  } > "$page"
  mkdir -p "$stage/assets/plugins/$slug"
  cp "$dir/assets/preview.png" "$stage/assets/plugins/$slug/preview.png"
  printf '\n## [%s](packages/%s.md)\n\n%s\n\n![%s preview](/assets/plugins/%s/preview.png)\n' "$name" "$slug" "$description" "$name" "$slug" >> "$index"
  count=$((count+1))
done
((count > 0)) || { echo "No plugin manifests in $root" >&2; exit 1; }
mkdir -p "$docs/content/plugins/packages" "$docs/assets/plugins"
for page in "$docs/content/plugins/packages/"*.md; do
  [[ -f $page ]] || continue
  slug=${page##*/}; slug=${slug%.md}
  if [[ ! -f $stage/content/plugins/packages/$slug.md && $(head -n 1 "$page") == "$header" ]]; then
    rm "$page"
    rm -f "$docs/assets/plugins/$slug/preview.png"
  fi
done
cp "$index" "$docs/content/plugins/catalog.md"
cp "$stage/content/plugins/packages/"*.md "$docs/content/plugins/packages/"
for preview in "$stage/assets/plugins/"*/preview.png; do
  slug=${preview%/preview.png}; slug=${slug##*/}
  mkdir -p "$docs/assets/plugins/$slug"
  cp "$preview" "$docs/assets/plugins/$slug/preview.png"
done
printf 'Generated %s plugin pages and previews in %s\n' "$count" "$docs"
