#!/usr/bin/env python3
"""Publish plugin manifests, READMEs and previews into a docs checkout."""

import argparse
import posixpath
import re
from pathlib import Path
from urllib.parse import urlsplit

import yaml

HEADER = "<!-- Generated by kumbuka-me/plugins scripts/docs. Edit the plugin README, manifest or preview in that repository. -->\n\n"
LINK = re.compile(r"(!?)\[([^\]]*)\]\(([^\s)]+)\)")
FENCE = re.compile(r"^\s{0,3}(`{3,}|~{3,})(.*)$")


def readme_body(text, slug):
    """Remove the title and resolve relative links outside fenced code blocks."""
    lines = text.strip().splitlines()
    if lines and lines[0].startswith("# "):
        lines.pop(0)

    def rewrite(match):
        image, label, target = match.groups()
        url = urlsplit(target)
        if url.scheme or target.startswith(("/", "#")):
            return match.group(0)
        base = "https://raw.githubusercontent.com/kumbuka-me/plugins/main/" if image else "https://github.com/kumbuka-me/plugins/blob/main/"
        return f"{image}[{label}]({base}{posixpath.normpath(slug + '/' + target)})"

    fence = ""
    output = []
    for line in lines:
        marker = FENCE.match(line)
        if fence:
            if marker and marker[1][0] == fence[0] and len(marker[1]) >= len(fence) and not marker[2].strip():
                fence = ""
        elif marker:
            fence = marker[1]
        else:
            line = LINK.sub(rewrite, line)
        output.append(line)
    return "\n".join(output).strip() + "\n"


def generate(root, docs):
    # Build and validate all outputs before modifying the documentation checkout.
    outputs = {}
    manifests = sorted(root.glob("*/plugin.yaml"))
    if not manifests:
        raise ValueError(f"No plugin manifests in {root}")
    index = HEADER + \
        "# Plugin catalog\n\nBrowse the first-party Kumbuka plugins. These pages follow the plugins repository's main branch; available releases are listed on each plugin's release page.\n\nSee [Plugin administration](../administration/plugins.md) for installation and updates.\n"
    for manifest in manifests:
        plugin = manifest.parent
        slug = plugin.name
        data = yaml.safe_load(manifest.read_text())
        if not isinstance(data, dict) or any(not isinstance(data.get(key), str) or not data[key].strip() for key in ("id", "name", "version", "description")):
            raise ValueError(f"{manifest}: missing or invalid plugin metadata")
        permissions = data.get("permissions") or []
        if not isinstance(permissions, list) or any(not isinstance(p, str) for p in permissions):
            raise ValueError(
                f"{manifest}: permissions must be a list of strings")
        readme = (plugin / "README.md").read_text()
        preview = (plugin / "assets/preview.png").read_bytes()
        if not readme.strip() or not preview:
            raise ValueError(f"{plugin}: empty README or preview")
        name, description = data["name"], data["description"]
        permission_text = ", ".join(f"`{p}`" for p in permissions) or "None"
        page = (
            HEADER + f"# {name}\n\n{description}\n\n"
            f"![{name} preview](/assets/plugins/{slug}/preview.png)\n\n"
            f"- Plugin ID: `{data['id']}`\n- Source version: `{data['version']}`\n- Permissions: {permission_text}\n\n"
            f"[Source](https://github.com/kumbuka-me/plugins/tree/main/{slug}) · "
            f"[Releases](https://github.com/kumbuka-me/plugins/releases?q={slug}%2Fv) · "
            "[Installation](../../administration/plugins.md)\n\n"
            + readme_body(readme, slug)
        )
        outputs[Path(f"content/plugins/packages/{slug}.md")] = page.encode()
        outputs[Path(f"assets/plugins/{slug}/preview.png")] = preview
        index += f"\n## [{name}](packages/{slug}.md)\n\n{description}\n\n![{name} preview](/assets/plugins/{slug}/preview.png)\n"
    outputs[Path("content/plugins/catalog.md")] = index.encode()
    for page in (docs / "content/plugins/packages").glob("*.md"):
        if page.relative_to(docs) not in outputs and page.read_text().startswith(HEADER):
            page.unlink()
            (docs /
             f"assets/plugins/{page.stem}/preview.png").unlink(missing_ok=True)
    for path, content in outputs.items():
        target = docs / path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(content)
    print(f"Generated {len(manifests)} plugin pages and previews in {docs}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--plugins", type=Path,
                        default=Path(__file__).resolve().parents[2])
    parser.add_argument("--docs", type=Path, default=Path("../docs"))
    args = parser.parse_args()
    try:
        generate(args.plugins.resolve(), args.docs.resolve())
    except (OSError, ValueError, yaml.YAMLError) as error:
        parser.exit(1, f"generate docs: {error}\n")
