// Command docs publishes plugin-owned documentation into a documentation checkout.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"go.yaml.in/yaml/v3"
)

const header = "<!-- Generated by kumbuka-me/plugins scripts/docs. Edit the plugin README, manifest or preview in that repository. -->\n\n"

type manifest struct {
	ID          string   `yaml:"id"`
	Name        string   `yaml:"name"`
	Version     string   `yaml:"version"`
	Description string   `yaml:"description"`
	Permissions []string `yaml:"permissions"`
}

var links = regexp.MustCompile(`(!?)\[([^\]]*)\]\(([^\s)]+)\)`)

// rewriteLinks preserves external and anchor links and resolves repository-relative links.
func rewriteLinks(body, slug string) string {
	return links.ReplaceAllStringFunc(body, func(link string) string {
		parts := links.FindStringSubmatch(link)
		target := parts[3]
		if strings.Contains(target, ":") || strings.HasPrefix(target, "#") || strings.HasPrefix(target, "/") {
			return link
		}
		base := "https://github.com/kumbuka-me/plugins/blob/main/"
		if parts[1] == "!" {
			base = "https://raw.githubusercontent.com/kumbuka-me/plugins/main/"
		}
		return parts[1] + "[" + parts[2] + "](" + base + filepath.ToSlash(filepath.Clean(filepath.Join(slug, target))) + ")"
	})
}

func write(path string, data []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return err
	}
	return os.WriteFile(path, data, 0644)
}

func generate(root, docs string) error {
	paths, err := filepath.Glob(filepath.Join(root, "*", "plugin.yaml"))
	if err != nil {
		return err
	}
	if len(paths) == 0 {
		return fmt.Errorf("no plugin manifests in %s", root)
	}
	// Validate every source before modifying the destination.
	outputs := map[string][]byte{}
	index := header + "# Plugin catalog\n\nBrowse the first-party Kumbuka plugins. These pages follow the plugins repository's main branch; available releases are listed on each plugin's release page.\n\nSee [Plugin administration](../administration/plugins.md) for installation and updates.\n"
	for _, path := range paths {
		dir := filepath.Dir(path)
		slug := filepath.Base(dir)
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		var m manifest
		if err := yaml.Unmarshal(data, &m); err != nil {
			return fmt.Errorf("%s: %w", path, err)
		}
		if m.ID == "" || m.Name == "" || m.Version == "" || m.Description == "" {
			return fmt.Errorf("%s: missing plugin metadata", path)
		}
		readme, err := os.ReadFile(filepath.Join(dir, "README.md"))
		if err != nil {
			return err
		}
		preview, err := os.ReadFile(filepath.Join(dir, "assets", "preview.png"))
		if err != nil {
			return err
		}
		if len(preview) == 0 || strings.TrimSpace(string(readme)) == "" {
			return fmt.Errorf("%s: empty README or preview", slug)
		}
		body := strings.TrimSpace(string(readme))
		if strings.HasPrefix(body, "# ") {
			_, body, _ = strings.Cut(body, "\n")
		}
		permissions := "None"
		if len(m.Permissions) > 0 {
			permissions = "`" + strings.Join(m.Permissions, "`, `") + "`"
		}
		page := header + fmt.Sprintf("# %s\n\n%s\n\n![%s preview](/assets/plugins/%s/preview.png)\n\n- Plugin ID: `%s`\n- Source version: `%s`\n- Permissions: %s\n\n[Source](https://github.com/kumbuka-me/plugins/tree/main/%s) · [Releases](https://github.com/kumbuka-me/plugins/releases?q=%s%%2Fv) · [Installation](../../administration/plugins.md)\n\n", m.Name, m.Description, m.Name, slug, m.ID, m.Version, permissions, slug, slug) + strings.TrimSpace(rewriteLinks(body, slug)) + "\n"
		outputs[filepath.Join("content", "plugins", "packages", slug+".md")] = []byte(page)
		outputs[filepath.Join("assets", "plugins", slug, "preview.png")] = preview
		index += fmt.Sprintf("\n## [%s](packages/%s.md)\n\n%s\n\n![%s preview](/assets/plugins/%s/preview.png)\n", m.Name, slug, m.Description, m.Name, slug)
	}
	outputs[filepath.Join("content", "plugins", "catalog.md")] = []byte(index)
	// Only remove stale pages bearing our ownership marker and their generated preview.
	stale, err := filepath.Glob(filepath.Join(docs, "content", "plugins", "packages", "*.md"))
	if err != nil {
		return err
	}
	for _, path := range stale {
		rel, err := filepath.Rel(docs, path)
		if err != nil {
			return err
		}
		if _, ok := outputs[rel]; ok {
			continue
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		if !strings.HasPrefix(string(data), header) {
			continue
		}
		if err := os.Remove(path); err != nil {
			return err
		}
		preview := filepath.Join(docs, "assets", "plugins", strings.TrimSuffix(filepath.Base(path), ".md"), "preview.png")
		if err := os.Remove(preview); err != nil && !os.IsNotExist(err) {
			return err
		}
	}
	for path, data := range outputs {
		if err := write(filepath.Join(docs, path), data); err != nil {
			return err
		}
	}
	fmt.Printf("Generated %d plugin pages and previews in %s\n", len(paths), docs)
	return nil
}

func main() {
	root := flag.String("plugins", ".", "Plugin repository")
	docs := flag.String("docs", "../docs", "Documentation repository")
	flag.Parse()
	if err := generate(*root, *docs); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
