api_version: 1
provider: Kumbuka
id: me.kumbuka.definition-lists
name: Definition Lists
version: 1.1.0
description: Add term and definition list syntax to Markdown.
default_enabled: false
modules:
  - type: markdown-syntax
    id: definition-lists
    syntax: definition-list
    usage:
      - contains: ":"
permissions: []
