api_version: 1
provider: Kumbuka
id: me.kumbuka.typographer
name: Typographer
version: 1.0.5
description: Convert common ASCII punctuation into typographic characters.
default_enabled: false
modules:
  - type: renderer-extension
    id: typographer
    stage: postprocess
permissions: []
