api_version: 1
provider: Kumbuka
id: me.kumbuka.typographer
name: Typographer
version: 1.0.1
description: Convert common ASCII punctuation into typographic characters.
default_enabled: false
modules:
  - type: render-policy
    id: typographer
    policy: typographer
permissions: []
