#!/usr/bin/env bash
# Exercise documentation generation and releases against disposable local fixtures.
set -euo pipefail
root=$(cd "$(dirname "$0")/../.." && pwd)
work=$(mktemp -d "${TMPDIR:-/tmp}/kumbuka-script-tests.XXXXXX")
trap 'rm -rf "$work"' EXIT
trap 'exit 130' INT
trap 'exit 143' TERM
for script in "$root"/scripts/*/*.sh; do bash -n "$script"; done
mkdir -p "$work/plugins/sample/assets" "$work/docs/content/plugins/packages" "$work/docs/assets/plugins/stale"
cat > "$work/plugins/sample/plugin.yaml" <<'YAML'
id: me.kumbuka.sample
name: 'Sample: plugin'
version: 1.0.0
description: >-
  A multiline
  description.
permissions: [pages:read]
YAML
printf '# Sample\n\n[Guide](../guide.md) ![Image](assets/example.png)\n' > "$work/plugins/sample/README.md"
printf preview > "$work/plugins/sample/assets/preview.png"
printf '# Manual\n' > "$work/docs/content/plugins/packages/manual.md"
printf '<!-- Generated by kumbuka-me/plugins scripts/docs. Edit the plugin README, manifest or preview in that repository. -->\n\nstale\n' > "$work/docs/content/plugins/packages/stale.md"
printf preview > "$work/docs/assets/plugins/stale/preview.png"
"$root/scripts/docs/generate.sh" --plugins "$work/plugins" --docs "$work/docs"
page="$work/docs/content/plugins/packages/sample.md"
grep -Fq 'A multiline description.' "$page"
grep -Fq 'blob/main/guide.md' "$page"
grep -Fq 'raw.githubusercontent.com/kumbuka-me/plugins/main/sample/assets/example.png' "$page"
[[ ! -f $work/docs/content/plugins/packages/stale.md && ! -f $work/docs/assets/plugins/stale/preview.png && -f $work/docs/content/plugins/packages/manual.md ]]
cp "$page" "$work/before.md"
"$root/scripts/docs/generate.sh" --plugins "$work/plugins" --docs "$work/docs"
cmp "$page" "$work/before.md"
rm "$work/plugins/sample/assets/preview.png"
if "$root/scripts/docs/generate.sh" --plugins "$work/plugins" --docs "$work/docs"; then echo 'Missing preview accepted' >&2; exit 1; fi
cmp "$page" "$work/before.md"

mkdir -p "$work/repository"
cp -R "$root/scripts" "$work/repository/"
cd "$work/repository"
for plugin in alpha beta; do mkdir "$plugin"; printf 'version: 1.2.3\n' > "$plugin/plugin.yaml"; done
git init -q -b main
git config commit.gpgsign false
git config tag.gpgsign false
git config user.name 'Script Tests'
git config user.email tests@example.invalid
git add .; git commit -qm initial
git init -q --bare "$work/remote.git"
git remote add origin "$work/remote.git"
git push -q origin main
cat > "$work/make" <<'MAKE'
#!/usr/bin/env bash
printf '%s\n' "$*" >> "$TEST_LOG"
[[ ${FAIL_CHECK:-0} == 0 ]]
MAKE
chmod +x "$work/make"
export RELEASE_MAKE="$work/make" TEST_LOG="$work/checks"
printf 'all\npatch\nn\n' | /bin/bash scripts/release/run.sh > "$work/cancel.log"
[[ -z $(git status --porcelain) && $(git rev-list --count HEAD) == 1 ]]
if printf '1\nminor\ny\n' | FAIL_CHECK=1 /bin/bash scripts/release/run.sh > "$work/failure.log" 2>&1; then echo 'Failed checks accepted' >&2; exit 1; fi
[[ -z $(git status --porcelain) && $(git rev-list --count HEAD) == 1 ]]
printf '9\n2,1-2\ncustom\nminor\nmajor\ny\n' | /bin/bash scripts/release/run.sh > "$work/release.log"
[[ $(scripts/version/read.sh alpha) == 1.3.0 && $(scripts/version/read.sh beta) == 2.0.0 ]]
[[ $(git rev-list --count HEAD) == 3 && -z $(git status --porcelain) ]]
[[ $(git --git-dir="$work/remote.git" rev-parse main) == "$(git rev-parse HEAD)" ]]
[[ $(git --git-dir="$work/remote.git" tag | wc -l | tr -d ' ') == 2 ]]
grep -Fxq 'build-plugin PLUGIN=alpha' "$work/checks"
grep -Fxq 'build-plugin PLUGIN=beta' "$work/checks"
# Existing remote tags must fail before changing manifests.
git --git-dir="$work/remote.git" tag alpha/v1.3.1
if printf '1\npatch\ny\n' | /bin/bash scripts/release/run.sh > "$work/collision.log" 2>&1; then echo 'Remote tag collision accepted' >&2; exit 1; fi
[[ -z $(git status --porcelain) && $(git rev-list --count HEAD) == 3 ]]
echo 'Shell integration tests passed.'
