api_version: 1
provider: Kumbuka
id: me.kumbuka.strikethrough
name: Strikethrough
version: 1.0.1
description: Render GitHub-style strikethrough text.
default_enabled: true
modules:
  - type: markdown-syntax
    id: strikethrough
    syntax: strikethrough
    usage:
      - contains: "~~"
permissions: []
