api_version: 1
provider: Kumbuka
id: me.kumbuka.footnotes
name: Footnotes
version: 1.0.7
description: Add Markdown footnote references and definitions.
default_enabled: false
modules:
  - type: markdown-syntax
    id: footnotes
    syntax: footnote
    usage:
      - contains: "[^"
permissions: []
